
---
- hosts: webservers
  tasks:
  - name: install apache2
    package: 
      name: apache2
      state: present 
  - name: start apache2 service 
    service:
      name: apache2
      state: started
      
...