
---
- hosts: webservers
  tasks:
  - name: Instalar httpdp
    package: 
      name: apache2
      state: present 
  - name: iniciar servicio httpd 
    service:
      name: apache2
      state: started
      
...